version: '3.8'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.20
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j.conf:/conf/neo4j.conf # This is the main configuration file.
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4juser/neo4jpass
      - NEO4JLABS_PLUGINS='["apoc", "n10s"]'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider localhost:7474 || exit 1',
        ]
    user: ${USER_ID}:${GROUP_ID}
    restart: always

networks:
  neo4j-internal:
