services:
  web-scraper:
    container_name: web-scraper
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./neo4j/import:/app/neo4j/import
    networks:
      - ollama-docker
    environment:
      - NEO4J_PASSWORD=neo4jpass

  neo4j:
    container_name: neo4j
    image: neo4j:5.20
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo4jpass
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_PLUGINS=["apoc", "n10s"]
    restart: always

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ['/usr/bin/bash', '/entrypoint.sh']
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  neo4j-internal:
  ollama-docker:
    external: false
